### ISSUE TITLE
The follow-users extension

### ISSUE THREAD

**Issue by jakebrowntech** [FreeFlarum/freeflarum.com#146]
__Packagist URL for extension:__
https://discuss.flarum.org/d/22628-follow-users-wip

__Why should we install this extension?__
You should install the extension because it will let users follow other users, as well as receive notifications when a user that they follow post.
This will help the community because it gives them an option to add this to their forums and make them more popular.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
The name should be Follow Users, and the description should be Follow users and be notified of new discussions and replies. Not sure if something went wrong, anyone with experiences can help would be greatly appreciated.

You can follow the user on the user profiles or user info in post view.

**Comment by CWKevo** [comment]
This is a duplicate request of #145. Next time, please don't create a new issue but merge the new information into the new one, either by editing your comment or simply by adding a new one.

Your anwer to the question whether this works on latest Flarum is not valid.

The rest of the request goes with the same answer I have made in the original #145. It is a WIP and author hasn't provided any update since January (he was last seen in February, so I believe he has moved on and won't probably finish the extension). I will leave this request open in case author comes back or in case others want it, but I doubt that.

**Comment by CWKevo** [comment]
Closed until this extension becomes stable enough - for now, it is not ready to be used in environment such as FreeFlarum. When there is an update, let us know and we will take a look at it.

**Comment by CWKevo** [comment]
Please see #415 for a possible alternative
