### ISSUE TITLE
clarkwinkelmann/flarum-ext-mailing

### ISSUE THREAD

**Issue by essesoul** [FreeFlarum/freeflarum.com#308]
__Packagist URL for extension:__
https://extiverse.com/extension/clarkwinkelmann/flarum-ext-mailing

__Why should we install the extension?__
Send individual or mass mailing to Flarum users.

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum. Does not apply to extension updates or "re-installations".
---

**Comment by CWKevo** [comment]
This won't be included right now. The main problem is that we have only 1 mail server, and if forums would send mass E-mails, it would raise the chance of some providers like Gmail to lower our reputation and mark us as spam.

Therefore, it likely won't be included in the near future either.

**Comment by essesoul** [comment]
Can you enable this extension for those websites that use their own mailbox?

**Comment by CWKevo** [comment]
Only if Flarum's `extend.php` allows us to put a check whether a forum has custom mail settings or not (all static files for all forums are synchronized and linked to save disk space, so that's why we have to use extenders to apply our logic).

I believe that it could be possible, but that would become very complicated really fast (query database to check if mail host and port is different than default, then apply a logic to disable that extension for other forums). Also, none of us is a PHP dev, so we simply don't know how to do that, even if it's possible.

**Comment by essesoul** [comment]
A small suggestion, if you can set certain restrictions on the local mail service after enabling this plug-in (for example, each site can only send 50 emails per hour), and encourage users to use their own mailbox, this may be able to cope with this problem .

**Comment by CWKevo** [comment]
> A small suggestion, if you can set certain restrictions on the local mail service after enabling this plug-in (for example, each site can only send 50 emails per hour), and encourage users to use their own mailbox, this may be able to cope with this problem .

Sadly, this is not possible. All forum names are recorded in a central database. Postfix (service that handles FF's outgoing and incoming E-mail) can't connect to MySQL (database service). We'd need some bridge for that, likely via Python (programming language that FF is written in). But here's the catch - Python cannot limit outgoing E-mail, and can't bridge to Postfix.

FreeFlarum is assembled via components and services that work independently on each other (Python for backend and frontend, PHP for serving Flarum, MySQL for handling database, Nginx for handling all requests, uWSGI to pass frontend and backend to Nginx and vice-versa, Postfix for E-mail + dozens of other smaller libraries).
Python can't work with PHP to listen when a forum enables an extension and limit E-mail via Postfix. Simply put, there is unfortunately no way to actually control or limit this *for individual forums* ([Postfix seems to be able to put a delay between E-mails, *globally*](http://www.postfix.org/postconf.5.html#default_destination_rate_delay))

In order for this to work, we'd need to have an extender for Flarum that does all of this. But since none of us knows how to program in PHP, this isn't happening either. Sorry, it's either "limit E-mail for all forums, so we can include this extension" or "keep current mail limitations and don't include this extension at all", sadly.

**Comment by SKevo18** [comment]
Update: FreeFlarum's mail server has matured since, and has quite a good reputation, which allowed me to include extensions such as `follow-tags`, `fof-subscribed`, etc... However, I am still a bit hesitant to add this, as it allows forum admins to send out mass e-mails with a click of a button. I can imagine that someone would abuse this at some point, to send out spam e-mails through FreeFlarum. I therefore consider this feature to not be adequate for a free forum hosting service, sorry.
