### ISSUE TITLE
blomstra/search

### ISSUE THREAD

**Issue by essesoul** [FreeFlarum/freeflarum.com#311]
__Packagist URL for extension:__
https://extiverse.com/extension/blomstra/search

__Why should we install the extension?__
Sync discussions to elastic search using your queue, unobtrusively for the user.
Reduces search loading times to well below 400ms (local tests with 50.000 discussion 260ms)
Uses Flarum's group permissions and tags system.
Compatible with Friends of Flarum Byōbu.

**Comment by CWKevo** [comment]
This requires us to run the `php flarum blomstra:search:build` command for each forum, so that the search dataset can be built. Further posts and discussions will be added manually, as the README states.

The search index will probably raise our disk space a bit. Also, currently there is not a general script to run a command for each forum. This extension might be included later

**Comment by zouyonghao** [comment]
> This requires us to run the `php flarum blomstra:search:build` command for each forum, so that the search dataset can be built. Further posts and discussions will be added manually, as the README states.
> 
> The search index will probably raise our disk space a bit. Also, currently there is not a general script to run a command for each forum. This extension might be included later though.

As I understand, this extension uses elastic, so maybe the disk space will not increase but it will assume some CPU resources for the forum enabled this extension.

**Comment by SKevo18** [comment]
Closing this for now (due to #362, see also #357 and #311 for more details)
