### ISSUE TITLE
zouyonghao/flarum-es

### ISSUE THREAD

**Issue by zouyonghao** [FreeFlarum/freeflarum.com#357]
__Packagist URL for extension:__
https://packagist.org/packages/zouyonghao/flarum-es

__Why should we install the extension?__
A simple support for elastic search with flarum.

**Comment by CWKevo** [comment]
Seems simple, however this extension has no discussion at Discuss, and it is not very clear what needs to be done in order to get the extension running (e. g.: how are indexes created, do we need to configure additional packages, etc...).

I am leaving this open for now until the extension becomes more mature.
