### ISSUE TITLE
Scout Search/package

### ISSUE THREAD

**Issue by peteryang1756** [FreeFlarum/freeflarum.com#362]
__Packagist URL for extension:__
https://extiverse.com/extension/clarkwinkelmann/flarum-ext-scout

__Why should we install the extension?__
Better search tools

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum.
---

**Comment by W1ndys** [comment]
> 我首先要从技术角度考虑是否可以将其包含在 FreeFlarum 中

Hello, I found that my current freeflarum search function is not very good. I can’t find the posts I should have found, so I also want to request to enable this extension.

**Comment by SKevo18** [comment]
This extension looks great in terms of extending the search functionality, however it requires additional setup:

- Indexes must be initially imported to Flarum using CLI. It is not possible for forum administrators to run CLI commands at FreeFlarum;
- Running this extension requires the search drivers to be properly set up, some require running additional system service to maintain the search index. Running a service for each FreeFlarum forum would negatively impact system resources even for forums that do not use the extension, since they are shared evenly across all forums;
- The extension is still quite experimental, and shouldn't be used in production

I think that by the time I would resolve these technical issues and figure out how to make it stable across all forums, Flarum would improve its search in core (this is planned for version +2.0, IIRC?). FreeFlarum is not meant for big forums anyways. Those that require better search functionality, as in the ability to search through thousands of posts with ease, should self-host their forum (and at that point, they can easily integrate this extension along with the required drivers).

> Hello, I found that my current freeflarum search function is not very good. I can’t find the posts I should have found, so I also want to request to enable this extension.

I assume that this request looks at it from the perspective of searching through a lot of content. If your content is Chinese, then I believe we can focus on improving search for Chinese characters instead (as that is not the purpose of the Scout extension). Some discussion was already done here, but again, I am not sure how possible is that to do on FreeFlarum's server without looking into it in more detail: https://discuss.flarum.org/d/22321
