### ISSUE TITLE
neerugupta/flarum-lang-arabic

### ISSUE THREAD

**Issue by medelinor-1** [FreeFlarum/freeflarum.com#380]
Packagist URL for extension:
https://packagist.org/packages/neerugupta/flarum-lang-arabic

Why should we install the extension?
I'm trying to create a Flarum forum in Arabic, and since Arabic is a right-to-left language, to use the Arabic forum well, you need to also add [flarum-ext-rtl](https://packagist.org/packages/irmmr/flarum-ext-rtl)
note:
This extension was [previously added](https://github.com/Free-Flarum/freeflarum.com/issues/354), and it was recently removed, I don't know why.
This extension accounts for **more than 50 percent of the user experience for Arabic or Hebrew language forums**.

With Regards

**Comment by CWKevo** [comment]
> This extension was [previously added](https://github.com/Free-Flarum/freeflarum.com/issues/354), and it was recently removed, I don't know why.

It was used by less than 3 % out of all FreeFlarum forums (likely because it's translations for core are completed by just [26 %](https://weblate.rob006.net/projects/flarum/core/ar/). I've explained why it was removed [here](https://discuss.flarum.org/d/7585/3828), and I also left that link in my issue comment before.

Anyways, I understand why you need this extension, so I might re-add it when FreeFlarum updates to Flarum 1.4.0.

**Comment by medelinor-1** [comment]
Hello

Thanks for the quick response

For right-to-left language forums, this is the most important extension applied to the forum.
What encouraged me to use Flarum at first was this extension.

**Note**: I have translated a large percentage of the forum's options into Arabic, and I have a file that I can download and share with you, if that helps. I also have experience in translating tools, and I would be glad to help with translation.

With Regards

**Comment by CWKevo** [comment]
If you are interested in helping with translations, then I don't manage that, but please check [this discussion](https://discuss.flarum.org/d/20807) - you can commit translations to the Weblate repository.

**Comment by CWKevo** [comment]
Added
