### ISSUE TITLE
WordPress Integration

### ISSUE THREAD

**Issue by ngoviminhhieu** [FreeFlarum/freeflarum.com#416]
### URL to the extension:
https://extiverse.com/extension/kilowhat/flarum-ext-wordpress

### Why should this extension be installed?
I would like to have it because it can help me develop a powerful forum

---
> ###### **Note**: All new extension requests require at least 5 upvotes (👍) before they can be added to FreeFlarum, excluding upvotes from alt accounts. If you are interested in this extension, please upvote this issue by adding the "👍" reaction to this comment. [Why?](https://discuss.flarum.org/d/7585/3828#:~:text=as%20a%20result%20of%20this%2C%20all%20extension%20requests%20must%20now%20provide%20a%20valid%20reason%20why%20should%20that%20extension%20be%20installed%2C%20and%20must%20have%20at%20least%205%20upvotes.%20Not%20following%20the%20template%20might%20result%20in%20your%20request%20being%20denied.)
---

**Comment by anewstudy** [comment]
wow

**Comment by CWKevo** [comment]
This extension is paid and can't be included at FreeFlarum.

**Comment by clarkwinkelmann** [comment]
Even if FreeFlarum somehow implemented Extiverse licensing, SSH access is quasi-required to use my WordPress extension due to things like CA bundles and recovering from any error if WordPress goes down.

Also, SSH is listed as one of the requirements without which I can't provide support for the extension.
