### ISSUE TITLE
Add ChatGPT Extension

### ISSUE THREAD

**Issue by Borderliner** [FreeFlarum/freeflarum.com#453]
### Extension URL

https://discuss.flarum.org/d/32535-chatgpt-ai-powered-auto-reply-extension-for-flarum/97

### Why should we install this extension?

Our forum involves user content creation, to it would be very useful if they can use this extension to generate content. I'm a donated user, please add this extension thanks!

**Comment by SKevo18** [comment]
Hi, normally I only review extension requests that have at around 5 upvotes to make sure people are interested in having the extension installed at their forums, but since requests rarely get this amount of upvotes, I am considering to change the extension request process in the future. I'll include this one right now to see how it works, thanks for the request!
